# Gin-Vue-Admin Global Configuration

# zap logger configuration
zap:
  level: 'debug'
  format: 'console'
  prefix: '[redisdual]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  #  stacktrace-key: 'stacktrace'
  log-in-console: true

# 执行时间间隔，单位毫秒
execinterval: 1

# 本地key前缀
localkeyprefix: a
remotekeyprefix: b

# redis configuration
redisrw:
  db: 0
  addr: '114.67.76.82:16375'
  password: 'redistest0102'

redisro:
  db: 0
  addr: '114.67.120.120:16375'
  password: 'redistest0102'



